server:
  port: 5000 # Elastic Beanstalk expects for Spring Boot Java apps to be deployed on port 5000...

spring:
  application:
    name: spring-boot-poc
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username: admin
    password: revature
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: create

management:
  endpoints:
    web:
      exposure:
        include: "*"